name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: jsoliveira
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}    
      -
        name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          tags: jsoliveira/orchestrator
          file: Dockerfile
          push: true
     